version: "3.7"

networks:
  net:
    driver: overlay
    attachable: true

services:
  app:
    image: syspass/syspass:3.2.2
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    environment:
    - USE_SSL=yes
    - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.2
    ports:
      - "80"
      - "443"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
         limits:
          cpus: "1"
          memory: 256M
    networks:
      - net

  db:
    image: mariadb:10.2
    volumes: 
      - syspass-db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=syspass
      - MYSQL_ROOT=% 
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: on-failure
      resources:
         limits:
          cpus: "1"
          memory: 256M
    networks:
      - net
